insert into BancosVzla values('0001','BANCO CENTRAL DE VENEZUELA');
insert into BancosVzla values('0102','BANCO DE VENEZUELA S.A.C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0104','VENEZOLANO DE CRÉDITO, S.A. BANCO UNIVERSAL');
insert into BancosVzla values('0105','BANCO MERCANTIL, C.A. S.A.C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0108','BANCO PROVINCIAL, S.A. BANCO UNIVERSAL');
insert into BancosVzla values('0114','BANCO DEL CARIBE, C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0115','BANCO EXTERIOR, C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0116','BANCO OCCIDENTAL DE DESCUENTO BANCO UNIVERSAL, C.A.');
insert into BancosVzla values('0128','BANCO CARONI, C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0134','BANESCO BANCO UNIVERSAL S.A.C.A.');
insert into BancosVzla values('0137','BANCO SOFITASA BANCO UNIVERSAL, C.A.');
insert into BancosVzla values('0138','BANCO PLAZA, BANCO UNIVERSAL C.A.');
insert into BancosVzla values('0146','BANCO DE LA GENTE EMPRENDEDORA BANGENTE, C.A.');
insert into BancosVzla values('0149','BANCO DEL PUEBLO SOBERANO, BANCO DE DESARROLLO');
insert into BancosVzla values('0151','BFC BANCO FONDO COMUN C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0157','DELSUR BANCO UNIVERSAL, C.A.');
insert into BancosVzla values('0163','BANCO DEL TESORO, C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0166','BANCO AGRICOLA DE VENEZUELA, C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0168','BANCRECER S.A. BANCO DE DESARROLLO');
insert into BancosVzla values('0169','MI BANCO, BANCO MICROFINANCIERO, C.A.');
insert into BancosVzla values('0171','BANCO ACTIVO, C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0172','BANCAMIGA BANCO MICROFINANCIERO, C.A.');
insert into BancosVzla values('0173','BANCO INTERNACIONAL DE DESARROLLO, C.A. BANCO UNIVERSAL');
insert into BancosVzla values('0174','BANPLUS BANCO UNIVERAL, C.A.');
insert into BancosVzla values('0175','BANCO BICENTENARIO BANCO UNIVERSAL, C.A.');
insert into BancosVzla values('0176','NOVO BANCO, S.A. SUCURSAL VENEZUELA BANCO UNIVERSAL');
insert into BancosVzla values('0177','BANCO DE LA FUERZA ARMADA NACIONAL BOLIVARIANA, B.U.');
insert into BancosVzla values('0190','CITIBANK N.A.');
insert into BancosVzla values('0191','BANCO NACIONAL CRÉDITO, C.A. BANCO UNIVERSAL');
